name: Sync KV secrets to repository secrets
on:
  workflow_call:
    inputs:
      env:
        description: 'Environment'
        required: true
        type: string
      terraform_version:
        description: 'Terraform version'
        required: true
        type: string
      runs-on: 
        description: 'Runs on'
        required: true
        type: string
      

    secrets:
        GH_PAT:
            description: 'GitHub PAT'
            required: true
        TENANT_ID:
            description: 'Tenant ID'
            required: true
        SUBSCRIPTION_ID:
            description: 'Subscription ID'
            required: true
        CLIENT_ID:
            description: 'Client ID'
            required: true
        CLIENT_SECRET:
            description: 'Client Secret'
            required: true
        KV_REPOSITORY_SECRETS:
            description: 'Key Vault Repository Secrets'
            required: true
        KV_REPOSITORY_SECRETS_RG_NAME:
            description: 'Key Vault Repository Secrets Resource Group Name'
            required: true
        TERRAFORM_RESOURCE_GROUP:
            description: 'Terraform Resource Group'
            required: true
        TERRAFORM_STORAGE_ACCOUNT_NAME:
            description: 'Terraform Storage Account Name'
            required: true
        TERRAFORM_CONTAINER_NAME:
            description: 'Terraform Container Name'
            required: true
        TERRAFORM_BACKEND_KEY_SYNC_SECRETS:
            description: 'Terraform Backend Key Sync Secrets'
            required: true
        
jobs:
  sync:
    name: Sync KV secrets to repository secrets
    runs-on: ${{ inputs.runs-on }}
    environment: ${{ inputs.env }}
    steps:
    - run: echo "Deploying to ${{ inputs.env }}"

    - name: checkout
      uses: actions/checkout@v2

    - name: install terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraform_version }}
        
    - name: az cli login
      uses: azure/login@v1
      with:
        creds: '{"tenantId": "${{ secrets.TENANT_ID }}", "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}", "clientId": "${{ secrets.CLIENT_ID }}", "clientSecret": "${{ secrets.CLIENT_SECRET }}"}'
        enable-AzPSSession: true

    - name: terraform arm credentials
      shell: bash
      run: |
        echo ARM_CLIENT_ID="${{ secrets.CLIENT_ID }}" >> "$GITHUB_ENV"
        echo ARM_CLIENT_SECRET="${{ secrets.CLIENT_SECRET }}" >> "$GITHUB_ENV"
        echo ARM_TENANT_ID="${{ secrets.TENANT_ID }}" >> "$GITHUB_ENV"
        echo ARM_SUBSCRIPTION_ID="${{ secrets.SUBSCRIPTION_ID }}" >> "$GITHUB_ENV"

    - name: pull secret names
      shell: bash
      run: |
        SECRETS=$(pwsh -command 'az keyvault secret list --vault-name ${{ vars.KV_REPOSITORY_SECRETS }} | convertfrom-json | ? { $_.name.StartsWith("${{ github.repository }}".Split("/")[1]) } | % { $output += $_.name + " " }; $output.Trim()')
        echo "SECRETS=$SECRETS" >> "$GITHUB_ENV"

    - name: terraform init
      shell: bash
      run: |
        terraform -chdir=$GITHUB_WORKSPACE/terraform/kv-to-repo-secrets/res init \
                  -reconfigure \
                  -backend-config=resource_group_name=${{ vars.TERRAFORM_RESOURCE_GROUP }} \
                  -backend-config=storage_account_name=${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }} \
                  -backend-config=container_name=${{ vars.TERRAFORM_CONTAINER_NAME }} \
                  -backend-config=key=${{ vars.TERRAFORM_BACKEND_KEY_SYNC_SECRETS }}

    - name: terraform destroy current secrets
      shell: bash
      run: |
        terraform -chdir=$GITHUB_WORKSPACE/terraform/kv-to-repo-secrets/res destroy \
                  --auto-approve \
                  -var azurerm_tenant_id=${{ secrets.TENANT_ID }} \
                  -var azurerm_client_id=${{ secrets.CLIENT_ID }} \
                  -var azurerm_client_secret=${{ secrets.CLIENT_SECRET }} \
                  -var azurerm_subscription_id=${{ secrets.SUBSCRIPTION_ID }} \
                  -var kv_name=${{ vars.KV_REPOSITORY_SECRETS }} \
                  -var kv_resource_group_name=${{ vars.KV_REPOSITORY_SECRETS_RG_NAME }} \
                  -var kv_secrets="$SECRETS" \
                  -var github_token=${{ secrets.GH_PAT }} \
                  -var github_owner=${{ github.repository_owner }} \
                  -var github_repository_name="${{ github.repository }}" \
                  -var github_repository_environment=${{ inputs.env }}

    - name: terraform apply new secrets
      shell: bash
      run: |
        terraform -chdir=$GITHUB_WORKSPACE/terraform/kv-to-repo-secrets/res apply \
                  --auto-approve \
                  -var azurerm_tenant_id=${{ secrets.TENANT_ID }} \
                  -var azurerm_client_id=${{ secrets.CLIENT_ID }} \
                  -var azurerm_client_secret=${{ secrets.CLIENT_SECRET }} \
                  -var azurerm_subscription_id=${{ secrets.SUBSCRIPTION_ID }} \
                  -var kv_name=${{ vars.KV_REPOSITORY_SECRETS }} \
                  -var kv_resource_group_name=${{ vars.KV_REPOSITORY_SECRETS_RG_NAME }} \
                  -var kv_secrets="$SECRETS" \
                  -var github_token=${{ secrets.GH_PAT }} \
                  -var github_owner=${{ github.repository_owner }} \
                  -var github_repository_name="${{ github.repository }}" \
                  -var github_repository_environment=${{ inputs.env }}

    - name: az cli Logout
      run: |
        az logout
        az cache purge
        az account clear
